import os

## STASH PRIVATE KEYS/SECRETS IN DOTENV/FLASKENV
ACCOUNT_NAME=''

AUTHORITY=''

REDIRECT_PATH=''

ENDPOINT='' # CAN BE USED TO CONNECT TO API ENDPOINTS

SCOPE='' # SCOPES FOR API

SESSION_TYPE=''

CONNECTION_STRING=''